/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_example_carapp_OBOJNI */

#ifndef _Included_com_example_carapp_OBOJNI
#define _Included_com_example_carapp_OBOJNI
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_example_carapp_OBOJNI
 * Method:    hello_jni
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_example_carapp_OBOJNI_hello_1jni
  (JNIEnv *, jobject);

/*
 * Class:     com_example_carapp_OBOJNI
 * Method:    test_jni_api
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_com_example_carapp_OBOJNI_test_1jni_1api
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     com_example_carapp_OBOJNI
 * Method:    test_jni_api2
 * Signature: (Z)Z
 */
JNIEXPORT jboolean JNICALL Java_com_example_carapp_OBOJNI_test_1jni_1api2
  (JNIEnv *, jobject, jboolean);

/*
 * Class:     com_example_carapp_OBOJNI
 * Method:    test_jni_api4_array
 * Signature: ([I)V
 */
JNIEXPORT void JNICALL Java_com_example_carapp_OBOJNI_test_1jni_1api4_1array
  (JNIEnv *, jobject, jintArray);

/*
 * Class:     com_example_carapp_OBOJNI
 * Method:    login
 * Signature: (Ljava/lang/String;Ljava/lang/String;Z)Z
 */
JNIEXPORT jboolean JNICALL Java_com_example_carapp_OBOJNI_login
  (JNIEnv *, jobject, jstring, jstring, jboolean);

#ifdef __cplusplus
}
#endif
#endif
